# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e8a12ca30a1f2eb12ad7cccdfa37adfed311ddf714a25e241c3422fa7d5457253adc5d0331b36209d659e32ddb0ff2197277707b59001546f276478b142f1bc

test:
  secret_key_base: 10e5633d8eacb1f6a2384b6257e18c48332fb7e6b8a5bedf87acb035f79f85330550c4f15571b905571110d2a2c6f321fcdab5da60e742b8e883a28e0596e04c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
